---
- name: Docker | Install docker and docker compose on CentOS 7
  hosts: homelab-docker
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Check if docker package is installed
      yum: list=docker
      register: is_docker

    - name: Remove old version
      yum: name='{{ item }}' state='absent'
      with_items: '{{ docker_old_component }}'
      when: is_docker

    - name: Install Docker dependencies
      yum: name='{{ item }}' state='present'
      with_items: '{{ docker_dependencies }}'

    - name: Add docker repository
      yum_repository: name=docker-'{{ docker_edition }}' description='docker stable repository' baseurl='{{ docker_repos }}'

    - name: Install Docker
      yum: name='docker' state='latest'

    - name: Install Docker Compose
      get_url: url='{{ docker_compose_url }}' dest='{{ docker_compose_dest }}' force=True owner='root' group='root' mode='0755'
      when: docker_install_docker_compose

    - name: ensure docker is running (and enable it at boot)
      service: name=docker state=started enabled=yes

  handlers:
  - name: Restart Docker
    service: name:='docker' state='restarted'
